server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://129.211.168.225:3306/test?characterEncoding=utf8&useSSL=true
    username: root
    password: 18039002
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*.xml